mod check_crud_io;
mod gen_create;
mod gen_delete;
mod gen_detail;
mod gen_search;
mod gen_update;
pub use check_crud_io::*;
mod gen_count;
pub use gen_count::*;
pub use gen_create::*;
pub use gen_delete::*;
pub use gen_detail::*;
pub use gen_search::*;
pub use gen_update::*;
